trunk/zvafzwects/src/de/fhkl/dbsm/zvafzwects/model/db/DBAlbum.java
package de.fhkl.dbsm.zvafzwects.model.db;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.SortedMap;
import java.util.TreeMap;

/**
 * @author Andreas Baur, Jochen Pätzold
 * @version 3
 */
public class DBAlbum {
	private int albumId;
	private String title;
	private String interpreter;
	private int numberOfCds;
	private BigDecimal price;
	private String label;
	private int stock;
	private int releaseYear;
	private DBCover cover;
	private DBCategory category;
	private SortedMap<Integer, DBCD> cds;
	private Set<DBCatchword> catchwords;

	public DBAlbum() {
		super();
		this.albumId = -1;
		this.cover = new DBCover();
		this.category = new DBCategory();
		this.price = new BigDecimal(0.00).setScale(2, RoundingMode.HALF_UP);
		this.cds = new TreeMap<Integer, DBCD>();
		this.catchwords = new LinkedHashSet<DBCatchword>();
	}

	public DBAlbum(String title, String interpreter, BigDecimal price,
			String label, int stock, DBCover cover, DBCategory category) {
		super();
		this.title = title;
		this.interpreter = interpreter;
		setPrice(price);
		this.label = label;
		this.stock = stock;
		this.cover = cover;
		this.category = category;
		this.cds = new TreeMap<Integer, DBCD>();
		this.catchwords = new LinkedHashSet<DBCatchword>();
	}

	public int getAlbumId() {
		return albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getInterpreter() {
		return interpreter;
	}

	public void setInterpreter(String interpreter) {
		this.interpreter = interpreter;
	}

	public int getNumberOfCds() {
		return numberOfCds;
	}

	public void setNumberOfCcds(int numberOfCds) {
		this.numberOfCds = numberOfCds;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public String getPriceAsString() {
		return price.toPlainString();
	}

	public void setPrice(BigDecimal price) {
		this.price = BigDecimal.valueOf(price.doubleValue()).setScale(2,
				RoundingMode.HALF_UP);
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public int getStock() {
		return stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public int getReleaseYear() {
		return releaseYear;
	}

	public void setReleaseYear(int releaseYear) {
		this.releaseYear = releaseYear;
	}

	public DBCover getCover() {
		return cover;
	}

	public void setCover(DBCover cover) {
		if (cover != null) {
			cover.setAlbumId(this.albumId);
		}
		this.cover = cover;
	}

	public DBCategory getCategory() {
		return category;
	}

	/**
	 * sets the category of an album. if you want to unset the category the
	 * parameter must be null
	 * 
	 * @param category the new category for the album. null to unset the
	 *            category of the album
	 */
	public void setCategory(DBCategory category) {
		// remove the album from the old category
		if (this.category != null)
			this.category.removeAlbum(this);
		// add the album to the new category
		if (category != null) {
			// set the new category
			this.category = category;
			category.addAlbum(this);
		} else {
			this.category = null;
		}
	}

	public Collection<DBCD> getCds() {
		return this.cds.values();
	}

	@Deprecated
	public void setCds(SortedMap<Integer, DBCD> cds) {
		this.cds = cds;
	}

	/**
	 * @param cdNumber the cd number to look for
	 * @return the cd found with the associated key, or null if no cd was found
	 */
	public DBCD getCd(int cdNumber) {
		return this.cds.get(cdNumber);
	}

	protected void addCd(DBCD cd) {
		if (this.cds.put(cd.getCdNumber(), cd) == null)
			this.numberOfCds++;
	}

	protected void removeCd(int cdNumber) {
		if (this.cds.remove(cdNumber) != null)
			this.numberOfCds--;
	}

	public Set<DBCatchword> getCatchwords() {
		return catchwords;
	}

	public void setCatchwords(Set<DBCatchword> catchwords) {
		// remove the album from the old catchwords
		if (!this.catchwords.isEmpty()) {
			for (DBCatchword cw : this.catchwords) {
				cw.removeAlbum(this);
			}
		}
		// set the catchword list
		this.catchwords = catchwords;
		// add the album to the new catchwords
		for (DBCatchword cw : catchwords) {
			cw.addAlbum(this);
		}
	}
}

trunk/zvafzwects/src/de/fhkl/dbsm/zvafzwects/model/db/DBUser.java
package de.fhkl.dbsm.zvafzwects.model.db;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * @author Andreas Baur, Jochen Pätzold
 */
public class DBUser {
	private int userId;
	private String surname;
	private String forename;
	private String email;
	private String password;
	private Date dateOfBirth;
	private char gender;
	private List<DBAddress> addresses;
	private List<DBOrder> orders;
	private boolean isAdmin;

	public DBUser() {
		super();
		addresses = new ArrayList<DBAddress>();
		orders = new ArrayList<DBOrder>();
	}

	public DBUser(String surname, String forename, String email,
			String password, Date dateOfBirth, char gender, boolean isAdmin) {
		super();
		this.surname = surname;
		this.forename = forename;
		this.email = email;
		this.password = password;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.isAdmin = isAdmin;
		addresses = new ArrayList<DBAddress>();
		orders = new ArrayList<DBOrder>();
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getForename() {
		return forename;
	}

	public void setForename(String forename) {
		this.forename = forename;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public String getDateOfBirthAsString() {
		if (dateOfBirth != null) {
			DateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");
			return formatter.format(dateOfBirth);
		}
		return "";
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	

	public char getGender() {
		return gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	public List<DBAddress> getAddresses() {
		return addresses;
	}

	public void setAddresses(List<DBAddress> addresses) {
		this.addresses = addresses;
	}

	public void addAddress(DBAddress address) {
		this.addresses.add(address);
	}

	public void removeAddress(DBAddress address) {
		if (addresses.isEmpty()) {
			return;
		}
		addresses.remove(address);
	}

	public List<DBOrder> getOrders() {
		return this.orders;
	}

	public void setOrders(List<DBOrder> orders) {
		this.orders = orders;
	}

	public void addOrder(DBOrder order) {
		this.orders.add(order);
	}

	public boolean getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public boolean addressExists(DBAddress address) {
		for (DBAddress addr : addresses) {
			if (addr.equals(address))
				return true;
		}
		return false;
	}
}

trunk/zvafzwects/WebContent/createaddress.jsp
<%@ include file="inc/before.jsp"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%-- Author: Andreas Baur --%>

<h1>Adresse anlegen</h1>

<div id="create_address">
	<form action="user?action=create_address" method="post">
		<c:choose>
			<c:when test="${not empty redirect}" >
				<input type="hidden" name="redirectParameter" value="<c:out value='${redirect}' />" />
			</c:when>
			<c:otherwise>
				<input type="hidden" name="redirectParameter" value="<c:out value='${header.referer}' />" />
			</c:otherwise>
		</c:choose>
		<div class="form_input">
			<label for="address_street">Straße: </label> 
			<input id="address_street" name="address_street" type="text" value="" />
		</div>
		<div class="form_input">
			<label for="address_housenumber">Hausnummer: </label> 
			<input id="address_housenumber" name="address_housenumber" type="text" value="" />
		</div>
		<div class="form_input">	
			<label for="address_zipcode">PLZ: </label> 
			<input id="address_zipcode" name="address_zipcode" type="text" value="" />
		</div>
		<div class="form_input">
			<label for="address_city">Stadt: </label> 
			<input id="address_city" name="address_city" type="text" value="" />
		</div>
		<div class="form_submit">
			<input class="form_submit_button" type="submit" value="Adresse anlegen" />
		</div>
	</form>
</div>

<%@ include file="inc/after.jsp"%>

trunk/zvafzwects/WebContent/editalbum.jsp
<%@ include file="inc/before.jsp" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://zvafzwects/myfn" prefix="myfn" %>
<%-- Author: Markus Henn, Jochen Pätzold --%>

<c:choose>
	<c:when test="${album.albumId > -1}">
		<h1>Album editieren</h1>
	</c:when>
	<c:otherwise>
		<h1>Neues Album hinzufügen</h1>
	</c:otherwise>
</c:choose>

<form id="editalbum" action="<c:out value='${formAction}' />" method="post" enctype="multipart/form-data">
	<div class="form_input title">
		<label for="album_title">Titel: </label>
		<input id="album_title" name="album_title" type="text" value="<c:out value='${album.title}' />" />
	</div>
	<div class="form_input interpreter">
		<label for="album_interpreter">Interpret: </label>
		<input id="album_interpreter" name="album_interpreter" type="text" value="<c:out value='${album.interpreter}' />" />
	</div>
	<div class="form_input category">
		<label for="album_category">Kategorie: </label>
		<select id="album_category" name="album_category">
			<option value="">Keine Kategorie</option>
			<c:forEach var="category" items="${categories}">
				<option value="${category.categoryId}"<c:if test='${(album.category != null) && (album.category.categoryId == category.categoryId)}'> selected="selected"</c:if>>
					<c:out value="${category.categoryName}" />
				</option>
			</c:forEach>
		</select> 
	</div>
	<div class="form_input catchwords">
		<label for="album_catchwords">Schlagworte: </label>
		<select id="album_catchwords" name="album_catchwords[]" multiple="multiple">
			<c:forEach var="catchword" items="${catchwords}">
				<option value="${catchword.catchwordId}"<c:if test='${(album.catchwords != null) && myfn:contains(album.catchwords, catchword)}'> selected="selected"</c:if>><c:out value="${catchword.catchwordName}" /></option>
			</c:forEach>
		</select> 
	</div>
	<div class="form_input releaseyear">
		<label for="album_releaseyear">Erscheinungsjahr: </label>
		<input id="album_releaseyear" name="album_releaseyear" type="text" value="<c:out value='${album.releaseYear}' />" />
	</div>
	<div class="form_input label">
		<label for="album_label">Label: </label>
		<input id="album_label" name="album_label" type="text" value="<c:out value='${album.label}' />" />
	</div>
	<c:if test="${album.cover != null}">
		<div class="album_cover_area">
			<img class="album_cover" src="cover?album_id=${album.albumId}" alt="album cover" />
		</div>
		<div class="form_input cover_delete">
			<label for="album_cover_delete">Cover entfernen: </label>
			<input id="album_cover_delete" name="album_cover_delete" type="checkbox" value="" />
		</div>
	</c:if>
	<div class="form_input cover">
			<label for="album_cover">Cover <c:if test="${album.cover != null}">ersetzen</c:if>: </label>
		<input id="album_cover" name="album_cover" type="file" value="" accept="image/*" />
	</div>
	<div class="form_input price">
		<label for="album_price">Preis: </label>
		<input id="album_price" name="album_price" type="text" value="<c:out value='${album.price}' />" /> €
	</div>
	<div class="form_input stock">
		<label for="album_stock">Stückzahl auf Lager: </label>
		<input id="album_stock" name="album_stock" type="text" value="<c:out value='${album.stock}' />" />
	</div>
	<c:if test="${!(album.albumId > -1)}">
		<div id="editalbum_cds">
			<noscript>
				Zum Hinzufügen von CDs (Tracks) wird JavaScript vorausgesetzt! JavaScript scheint in Ihrem Browser derzeit deaktiviert zu sein bzw. nicht unterstützt zu werden!
			</noscript>
		</div>
		<div>
			<button onclick="addNewCdInput(document.getElementById('editalbum_cds')); return false;">Weitere CD hinzufügen…</button>
		</div>
	</c:if>
	<div class="form_submit">
		<c:choose>
			<c:when test="${album.albumId > -1}">
				<input class="form_submit_button" type="submit" value="Editierte Albumdaten übernehmen" />
			</c:when>
			<c:otherwise>
				<input class="form_submit_button" type="submit" value="Album anlegen" />
			</c:otherwise>
		</c:choose>
	</div>
</form>

<%@ include file="inc/after.jsp" %>

trunk/zvafzwects/WebContent/editcatchword.jsp
<%@ include file="inc/before.jsp"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%-- Author: Andreas Baur --%>

<c:choose>
	<c:when test="${empty catchword}">	
		<h1>Neues Schlagwort anlegen</h1>
	</c:when>
	<c:otherwise>
		<h1>Schlagwort umbenennen</h1>
	</c:otherwise>
</c:choose>

<div id="create_catchword">
	<form action="<c:out value='${formAction}' />" method="post">
		<div class="form_input">
			<label for="catchword_name">Schlagwort: </label> <input
				id="catchword_name" name="catchword_name" type="text" value="<c:out value='${catchword.catchwordName}' />" />
		</div>
		<div class="form_submit">
			<c:choose>
			<c:when test="${empty catchword}">	
				<input class="form_submit_button" type="submit" value="Schlagwort anlegen" />
			</c:when>
			<c:otherwise>
				<input class="form_submit_button" type="submit" value="Schlagwort umbenennen" />
			</c:otherwise>
		</c:choose>
		</div>
	</form>
	
	<h2>Existierende Schlagworte:</h2>
	<div class="catchwords">
		<c:forEach var="catchword" items="${catchwords}">
			<div class="album_catchword">
				<a class="album_catchword" href="user?action=search&amp;album_catchwords[]=${catchword.catchwordId}"><c:out value="${catchword.catchwordName}" /></a>
				<a class="album_catchword_edit" href="admin?action=display_edit_catchword&amp;display_catchword_id=${catchword.catchwordId}">umbenennen</a>
				<a class="album_catchword_delete" href="admin?action=delete_catchword&amp;catchword_id=${catchword.catchwordId}">löschen</a>
			</div>
		</c:forEach>
	</div>
</div>

<%@ include file="inc/after.jsp"%>

trunk/zvafzwects/WebContent/editcategory.jsp
<%@ include file="inc/before.jsp"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%-- Author: Andreas Baur --%>

<c:choose>
	<c:when test="${empty category}">	
		<h1>Neue Kategorie anlegen</h1>
	</c:when>
	<c:otherwise>
		<h1>Kategorie umbenennen</h1>
	</c:otherwise>
</c:choose>

<form id="create_category" action="<c:out value='${formAction}' />" method="post">
	<div class="form_input">
		<label for="category_name">Kategorie: </label> <input
			id="category_name" name="category_name" type="text" value="<c:out value='${category.categoryName}' />" />
	</div>
	<div class="form_submit">
		<c:choose>
			<c:when test="${empty category}">	
				<input class="form_submit_button" type="submit" value="Kategorie anlegen" />
			</c:when>
			<c:otherwise>
				<input class="form_submit_button" type="submit" value="Kategorie umbenennen" />
			</c:otherwise>
		</c:choose>
	</div>
</form>

<h2>Existierende Kategorien:</h2>
<div class="categories">
	<c:forEach var="category" items="${categories}">
		<div class="album_category">
			<a class="album_category" href="user?action=search&amp;album_category=${category.categoryId}"><c:out value="${category.categoryName}" /></a>
			<a class="album_category_edit" href="admin?action=display_edit_category&amp;display_category_id=${category.categoryId}">umbenennen</a>
			<a class="album_category_delete" href="admin?action=delete_category&amp;category_id=${category.categoryId}">löschen</a>
		</div>
	</c:forEach>
</div>

<%@ include file="inc/after.jsp"%>

trunk/zvafzwects/WebContent/edituser.jsp
<%@ include file="inc/before.jsp"%>

<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%-- Author: Jochen Pätzold, Andreas Baur --%>

<c:choose>
	<c:when test="${empty user}">
		<h1>Registrierung</h1>
	</c:when>
	<c:otherwise>
		<h1>Profil editieren</h1>
	</c:otherwise>
</c:choose>

<form id="edituser" action="<c:out value='${formAction}' />"
	method="post">

	<div class="form_input">
		<label for="user_surname">Nachname: </label> <input id="user_surname"
			name="user_surname" type="text"
			value="<c:out value='${user.surname}' />" />
	</div>
	<div class="form_input">
		<label for="user_forename">Vorname: </label> <input id="user_forename"
			name="user_forename" type="text"
			value="<c:out value='${user.forename}' />" />
	</div>
	<div class="form_input">
		<label for="user_date_of_birth">Geburtsdatum: </label> <input
			id="user_date_of_birth" name="user_date_of_birth" type="date"
			value="<c:out value='${user.dateOfBirthAsString}' />" />
	</div>
	<div class="form_input">
		<label for="user_gender">Geschlecht: </label> <input type="radio"
			name="user_gender" value="m"
			<c:if test="${not empty user && 'm' == user.gender.toString()}"> checked="checked" </c:if>>
		m &nbsp; <input type="radio" name="user_gender" value="w"
			<c:if test="${not empty user && 'w' == user.gender.toString()}"> checked="checked" </c:if>>
		w <br />
	</div>
	<div class="form_input">
		<label for="user_email">E-Mail-Adresse: </label> <input
			id="user_email" name="user_email" type="email"
			value="<c:out value='${user.email}' />" />
	</div>
	<c:if test="${not empty user}">
		<label>Passwortänderung ist optional</label>
		<div class="form_input">
			<label for="user_password_new">Neues Passwort: </label> <input
				id="user_password_new" name="user_password_new" type="password"
				value="" />
		</div>
		<div class="form_input">
			<label for="user_password_approve">Passwort wiederholen: </label> <input
				id="user_password_approve" name="user_password_approve"
				type="password" value="" />
		</div>
	</c:if>
	<div class="form_input">
		<c:choose>
			<c:when test="${empty user}">
				<label for="user_password">Passwort: </label>
			</c:when>
			<c:otherwise>
				<label for="user_password">Passwort eingeben, um Änderungen
					zu übernehmen:</label>
			</c:otherwise>
		</c:choose>
		<input id="user_password" name="user_password" type="password"
			value="" />
	</div>
	<div class="form_submit">
		<c:choose>
			<c:when test="${empty user}">
				<input class="form_submit_button" type="submit" value="Registrieren" />
			</c:when>
			<c:otherwise>
				<input class="form_submit_button" type="submit" value="Übernehmen" />
			</c:otherwise>
		</c:choose>
	</div>
</form>
<c:if test="${not empty user}">
				<h2>Adressen</h2>
				<c:forEach var="address" items="${user.addresses}">
					<div class="address">
						<c:out value="${address.street}" /> <c:out value="${address.houseNumber}" />,
						<c:out value="${address.zipcode}" /> <c:out value="${address.city}" />
					</div>
				</c:forEach>
	<div>
		<a href="user?action=display_create_address">weitere Adresse anlegen</a>
	</div>
</c:if>

<%@ include file="inc/after.jsp"%>

trunk/zvafzwects/WebContent/error.jsp
<%@ include file="inc/before.jsp" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ include file="inc/after.jsp" %>

trunk/zvafzwects/WebContent/index.jsp
<%@ include file="inc/before.jsp" %>
<h1>MP3 Webshop</h1>
<div>
	Willkommen beim MP3-Webshop der Zukunft!
	Hier finden Sie alles, was das Herz begehrt, von A wie Alternative bis Z wie ZVAFZWECTS.</div>
<%@ include file="inc/after.jsp" %>

trunk/zvafzwects/WebContent/login.jsp
<%@ include file="inc/before.jsp" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%-- Author: Markus Henn --%>

<h1>Anmelden</h1>
<form id="login" action="user?action=login" method="post">
	<c:choose>
		<c:when test="${not empty redirectParameter}">
			<input type="hidden" name="redirectParameter" value="<c:out value='${redirectParameter}' />" />
		</c:when>
		<c:otherwise>
			<input type="hidden" name="redirectParameter" value="<c:out value='${header.referer}' default="" />" />
		</c:otherwise>
	</c:choose>
	<div class="form_input">
		<label for="login_email">E-Mail-Adresse: </label>
		<input id="login_email" name="login_email" type="text" value="" />
	</div>
	<div class="form_input">
		<label for="login_password">Passwort: </label>
		<input id="login_password" name="login_password" type="password" value="" />
	</div>
	<div class="form_submit">
		<input class="form_submit_button" type="submit" value="Anmelden" />
	</div>
</form>

<%@ include file="inc/after.jsp" %>

trunk/zvafzwects/WebContent/redirect.jsp
<%@ include file="inc/before.jsp" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%-- Author: Markus Henn --%>

<h1>Automatische Weiterleitung</h1>
<div>Sie werden in 5 Sekunden auf Ihre Ausgangsseite weitergeleitet.<br />
Alternativ können sie folgenden Link verwenden:
	<a href="<c:out value="${redirect}" />"><c:out value="${redirect}" /></a>
</div>
<%@ include file="inc/after.jsp" %>

trunk/zvafzwects/WebContent/viewalbum.jsp
<%@ include file="inc/before.jsp" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%-- Author: Markus Henn --%>

<h1 class="album_title"><c:out value="${album.title}" /></h1>
<%--<div class="album_interpreter">von: <a href="user?action=search&amp;album_interpreter=<%= java.net.URLEncoder.encode(((DBAlbum)request.getAttribute("album")).getInterpreter(), "utf-8") %>"><c:out value="${album.interpreter}" /></a></div>--%>
<div class="album_interpreter">von: <a href="user?action=search&amp;album_interpreter=<c:out value="${album.interpreter}" />"><c:out value="${album.interpreter}" /></a></div>

<div class="album_cover_area">
	<c:choose>
		<c:when test="${not empty album.cover}">
			<img class="album_cover" src="cover?album_id=${album.albumId}" alt="album cover" />
		</c:when>
		<c:otherwise>
			<img class="album_cover" src="https://upload.wikimedia.org/wikipedia/commons/d/d7/No_Cover_.jpg" alt="album cover" />
		</c:otherwise>
	</c:choose>
</div>

<div class="album_label">erschienen bei: <c:out value="${album.label}" /></div>
<div class="album_releaseyear">Erscheinungsjahr: <c:out value="${album.releaseYear}" /></div>
<div class="album_stock">noch <c:out value="${album.stock}" /> Stück auf Lager</div>
<div class="album_numberofcds"><c:out value="${album.numberOfCds}" /> CD(s)</div>
<div class="album_price"><c:out value="${album.priceAsString}" /> €</div>

<c:if test="${not empty album.category}">
	Kategorie:
	<div class="album_category">
		<a href="user?action=search&amp;album_category=${album.category.categoryId}"><c:out value="${album.category.categoryName}" /></a>
	</div>
</c:if>

<c:if test="${not empty album.catchwords}">
	Schlagwörter:
	<div class="album_catchwords">
		<c:forEach var="catchword" items="${album.catchwords}">
			<a class="album_catchword" href="user?action=search&amp;album_catchwords[]=${catchword.catchwordId}"><c:out value="${catchword.catchwordName}" /></a>
		</c:forEach>	
	</div>
</c:if>

<c:forEach var="cd" items="${album.cds}">
	<div class="cd">
		CD <c:out value="${cd.cdNumber}" />
		<c:forEach var="track" items="${cd.tracks}">
			<div class="track">
				<div class="track_number"><c:out value="${track.trackNumber}" />.</div>
				<div class="track_preview">
					<%--
					<form action="mp3stream" method="get">
						<input name="album_id" type="hidden" value="${album.albumId}" />
						<input name="cd_number" type="hidden" value="${cd.cdNumber}" />
						<input name="track_number" type="hidden" value="${track.trackNumber}" />
						<input type="submit" value="anhören" />
					</form>
					--%>
					<%--<a href="mp3stream?album_id=${album.albumId}&cd_number=${cd.cdNumber}&track_number=${track.trackNumber}">anhören</a>--%>
					<%--<embed src="audioplay/audioplay.swf?repeat=1&amp;buttondir=audioplay/buttons/classic_small&amp;file=MP3Stream%3Falbum_id%3D${album.albumId}%26cd_number%3D${cd.cdNumber}%26track_number%3D${track.trackNumber}" type="application/x-shockwave-flash"></embed>--%>
					<object type="application/x-shockwave-flash" data="audioplay/audioplay.swf?repeat=1&amp;buttondir=audioplay/buttons/classic_small&amp;fadeindur=1000&amp;file=mp3stream%3Falbum_id%3D${album.albumId}%26cd_number%3D${cd.cdNumber}%26track_number%3D${track.trackNumber}">
					</object>
				</div>
				<div class="track_title"><c:out value="${track.title}" /></div>
			</div>
		</c:forEach>
	</div>
</c:forEach>

<div>
	<form action="user?action=order_item&album_id=${album.albumId}" method="post">
		<input id="order_item_amount" name="order_item_amount" type="number" min="1" max="${album.stock}" value="1" />
		<label for="order_item_amount">Stück</label>
		<input type="submit" value="in den Warenkorb legen!" />
	</form>
</div>

<c:if test="${user.isAdmin}">
	<div class="admin_functions_area">
		<a href="admin?action=display_edit_album&amp;album_id=${album.albumId}">Album editieren</a>
	</div>
</c:if>

<%@ include file="inc/after.jsp" %>